version: '3.8'
services:

  #Frontend (Vue.js)
  ui:
    build:
      context: .
      dockerfile: ./docker/ui/Dockerfile
    container_name: ui
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
    environment:
      SERVICE_NAME: ui
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
